services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # Thêm dòng này
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
      - datanode # Thêm phần này ()

  # Thêm phần này
  kafka-cli:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-cli
    depends_on:
      - zookeeper
      - kafka
    entrypoint: /bin/bash
    tty: true


  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - namenode:/hadoop/dfs/name
      - hadoop_conf:/opt/hadoop/conf  # Chia sẻ cấu hình HDFS với Spark
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - datanode:/hadoop/dfs/data
      - hadoop_conf:/opt/hadoop/conf  # Đồng bộ cấu hình từ namenode
    depends_on:
      - namenode

  spark-master:
    image: apache/spark:3.5.0
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000  # Cấu hình HDFS cho Spark
      - HADOOP_CONF_DIR=/opt/hadoop/conf  # Đường dẫn đến cấu hình HDFS
    volumes:
      - hadoop_conf:/opt/hadoop/conf  # Mount cấu hình HDFS
    depends_on:
      - namenode
      - datanode
      - kafka

  spark-worker:
    image: apache/spark:3.5.0
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=4G # Thêm spark worker memory
      - SPARK_WORKER_CORES=4 # Thêm spark worker cores
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000  # Cấu hình HDFS cho Spark
      - HADOOP_CONF_DIR=/opt/hadoop/conf  # Đường dẫn đến cấu hình HDFS
    volumes:
      - hadoop_conf:/opt/hadoop/conf  # Mount cấu hình HDFS
    depends_on:
      - spark-master

  # sửa phần này
  model-service-gspc:
    build: ./model_service
    container_name: model-service-gspc
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - KAFKA_BOOTSTRAP=kafka:9092
      - COMPANY=GSPC
      - INPUT_TOPIC=daily_prices_GSPC
      # - OUTPUT_TOPIC=predictions
      # Sửa phần này
      - WINDOW_SIZE=3
    volumes:
      - ./model_service:/app
    depends_on:
      - kafka
      - spark-master
      
    # Thêm phần này
    user: root
  model-service-xom:
    build: ./model_service
    container_name: model-service-xom
    ports:
      - "8001:8000"
    environment:
      - PORT=8001
      - KAFKA_BOOTSTRAP=kafka:9092
      - COMPANY=XOM
      - INPUT_TOPIC=daily_prices_XOM
      # - OUTPUT_TOPIC=predictions
      # Sửa phần này
      - WINDOW_SIZE=3
    volumes:
      - ./model_service:/app
    depends_on:
      - kafka
      - spark-master
  
    # thêm phần này
    user: root
  model-service-cvx:
    build: ./model_service
    container_name: model-service-cvx
    ports:
      - "8002:8000"
    environment:
      - PORT=8002
      - KAFKA_BOOTSTRAP=kafka:9092
      - COMPANY=CVX
      - INPUT_TOPIC=daily_prices_CVX
      # - OUTPUT_TOPIC=predictions
      # Sửa phần này
      - WINDOW_SIZE=3
    volumes:
      - ./model_service:/app
    depends_on:
      - kafka
      - spark-master
      
    # Thêm phần này
    user: root
  model-service-bp:
    build: ./model_service
    container_name: model-service-bp
    ports:
      - "8003:8000"
    environment:
      - PORT=8003
      - KAFKA_BOOTSTRAP=kafka:9092
      - COMPANY=BP
      - INPUT_TOPIC=daily_prices_BP
      # - OUTPUT_TOPIC=predictions
      # Sửa phần này
      - WINDOW_SIZE=3
    volumes:
      - ./model_service:/app
    depends_on:
      - kafka
      - spark-master 
     
    # Thêm phần này
    user: root   

  kafka-producer:
    build: ./kafka-producer
    image: kafka-producer:latest # Thêm tên image
    container_name: kafka-producer
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - HISTORICAL_TOPIC_GSPC=historical_prices_GSPC
      - DAILY_TOPIC_GSPC=daily_prices_GSPC
      - TICKER=^GSPC
      # Thêm phần này
      - TICKER_XOM=XOM #XOM
      - HISTORICAL_TOPIC_XOM=historical_prices_XOM
      - DAILY_TOPIC_XOM=daily_prices_XOM
      - TICKER_CVX=CVX #CVX
      - HISTORICAL_TOPIC_CVX=historical_prices_CVX
      - DAILY_TOPIC_CVX=daily_prices_CVX
      - TICKER_BP=BP #BP
      - HISTORICAL_TOPIC_BP=historical_prices_BP
      - DAILY_TOPIC_BP=daily_prices_BP

      - POLL_INTERVAL_SECONDS=60
    volumes:
      - ./kafka-producer:/app
    depends_on:
      - kafka

  # spark-jobs:
  #   build: ./spark-jobs
  #   depends_on:
  #     - spark-master
  #     - spark-worker # Thêm cái này ()
  #     - namenode
  #     - kafka
  #     # Thêm cái này (không chắc)
  #     - kafka-producer
  #   environment:
  #     - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000  # Cấu hình HDFS cho Spark
  #     - HADOOP_CONF_DIR=/opt/hadoop/conf  # Đường dẫn đến cấu hình HDFS
  #   volumes:
  #     - ./spark-jobs:/app
  #     - hadoop_conf:/opt/hadoop/conf  # Mount cấu hình HDFS
  #   command: >
  #     /opt/spark/bin/spark-submit
  #     --master spark://spark-master:7077
  #     --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.apache.hadoop:hadoop-client:3.3.4
  #     /app/save_to_hdfs_job.py

  # train-job:
  #   build: ./spark-jobs
  #   depends_on:
  #     - spark-master
  #     - namenode
  #     #- spark-jobs  Bỏ cái này
  #   command: >
  #     /opt/spark/bin/spark-submit
  #     --master spark://spark-master:7077
  #     --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.apache.hadoop:hadoop-client:3.3.4
  #     /app/train_job.py
  #   volumes:
  #     - ./model_service:/models
  #     - ./spark-jobs:/app
  #     - hadoop_conf:/opt/hadoop/conf  # Mount cấu hình HDFS
  #   environment:
  #     - SPARK_HADOOP_FS_DEFAULTFS=hdfs://namenode:9000  # Cấu hình HDFS cho Spark
  #     - HADOOP_CONF_DIR=/opt/hadoop/conf  # Đường dẫn đến cấu hình HDFS
  #     # Bỏ đường dẫn này
  #     # - MODEL_SAVE_PATH=/models/risk_model.joblib
  #   user: root

  # Thêm fraud-detection
  # fraud-train:
  #   build: ./fraud-train
  #   container_name: fraud-train
  #   environment:
  #     DATA_PATH: /app/data/train_transaction.csv
  #     MODEL_PATH: /app/model/fraud_xgb_pipeline.pkl
  #   volumes:
  #     - ./data:/app/data      # mount dữ liệu vào container
  #     - ./model:/app/model    # mount thư mục model ra local
  #   command: python train_fraud_model.py
    
  # Thêm fraud-inference
  fraud-inference:
    build: ./fraud-inference
    container_name: fraud-app
    environment:
      - MODEL_PATH=/app/model/fraud_xgb_pipeline.pkl
      - BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./model:/app/model
    ports:
      - "8060:8060"
    depends_on:
      - kafka
      # - fraud-train
    user: root
  
  fraud-producer:
    build: ./fraud-inference
    container_name: fraud-producer
    command: ["python", "kafka_producer.py"]
    depends_on:
      - kafka
    volumes:
      - ./data:/app/data
  
  fraud-consumer:
    build: ./fraud-inference
    container_name: fraud-consumer
    command: ["python", "kafka_consumer.py"]
    depends_on:
      - kafka
      - fraud-inference
  
  # Thêm redis service + volume
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


# Setup các môi trường: database, airflow inint, webserver, scheduler của Apache Airflow services
  postgres-airflow:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow_db:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Chỉ mở nếu bạn cần truy cập DB từ bên ngoài
    # Thêm healthcheck để các service khác biết khi nào DB sẵn sàng
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  # === WEB SERVER ĐÃ CẬP NHẬT ===
  airflow-webserver:
    image: apache/airflow:2.8.1
    command: webserver
    ports:
      - "8088:8080" # Đã đổi cổng
    depends_on:
      airflow-init:
        # Chỉ khởi động SAU KHI airflow-init đã chạy xong và thành công
        condition: service_completed_successfully
    environment: &airflow-common-env # Dùng anchor để tái sử dụng biến môi trường cho gọn
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes: &airflow-common-volumes # Dùng anchor để tái sử dụng volumes
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: always 

  # === SCHEDULER ĐÃ CẬP NHẬT ===
  airflow-scheduler:
    image: apache/airflow:2.8.1
    command: scheduler
    depends_on:
      airflow-init:
        # Chỉ khởi động SAU KHI airflow-init đã chạy xong và thành công
        condition: service_completed_successfully
    environment: *airflow-common-env # Tái sử dụng environment ở trên
    volumes: 
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      # Thêm phần này
      # --- THÊM DÒNG NÀY ĐỂ AIRFLOW THẤY CODE SPARK ---
      - ./spark-jobs:/app
      - hadoop_conf:/opt/hadoop/conf  # Nếu script cần config HDFS 
      # Thêm dòng này để airflow thấy code fraud train
      - ./fraud-train:/app
    restart: always

  # === SERVICE MỚI ĐỂ KHỞI TẠO DATABASE ===
  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      postgres-airflow:
        # Chờ cho đến khi postgres-airflow "healthy"
        condition: service_healthy 
    environment: *airflow-common-env
    # Dùng airflow db migrate thay vì init
    command: >
      bash -c "airflow db migrate && 
               airflow users create --role Admin --username admin --password admin --email admin@example.com --firstname admin --lastname admin"


# API for UI-web
  dashboard-api:
    build: ./dashboard-api
    ports:
      - "8501:8000"  # Chúng ta sẽ truy cập dashboard tại http://localhost:8501
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - model-service-gspc # Chờ các model service chạy
      - fraud-consumer     # Chờ fraud consumer chạy
    volumes:
      - ./dashboard-api:/app # Mount code để tự động reload khi sửa (tùy chọn)

volumes:
  namenode:
  datanode:
  hadoop_conf:  # Volume mới để chia sẻ cấu hình HDFS
  redis_data: # Volume cho Redis
  airflow_db: # Volume cho PostgreSQL của Airflow
